kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.app }}
  namespace: minio
  labels:
    app: {{ .Values.app }}
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
