apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/artifacts/minio
    repoURL: 'https://github.com/AssistNavAI/NavAI.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true