apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navai
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: gitops/artifacts
    repoURL: 'https://github.com/AssistNavAI/NavAI.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true